[package]
name = "ur-lucky/greentealeaf"
version = "0.5.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

# Includes override excludes, and excludes is by default empty.
# We exclude everything, then include only what we want.
exclude = ["*"]
include = [
	"default.project.json",
	"src",
	"src/**",
	"wally.toml",
	"README.md",
	"CHANGELOG.md",
	"selene.toml",
	".luaurc",
]
